### ISSUE TITLE
NLO charge radius file ordering bug

### ISSUE THREAD

**Issue by basilirob** [e-eight/chime#6]
When generating charge radius files, the order defaults to:
lo, n2lo, n3lo, n4lo, nlo

This means that the only way to get the nlo file is to set the target as nlo explicitly; then you get a file for lo, n2lo, n3lo, n4lo, nlo, and an nlo_cumulative file which actually is the sum of all of them (so its really a 'n4lo_cumulative' file). Note also the n2lo and n4lo files have all 0 elements (n2lo because it has no contribution, n4lo since it isn't done yet for 2b).

Note that this means the cumulative files for >= n2lo miss the nlo correction (finite radius).

**Comment by e-eight** [comment]
This is fixed on commit https://github.com/e-eight/chime/commit/44394ab7632444a4d01c942e2e8971d3b927fb19.

The issue was because `std::map` is sorted using `operator<`. `std::map` was used to map the input `order` string to an element of the enum class `Order`. I have currently replaced the `std::map` with an `std::unordered_map` (for O(1) run time, thought for the small number of cases that we have it is not important) + `std::vector` (for desired sorting order) combination. This can be possibly replaced with a `boost::multiindex` or something like `tsl::ordered_map`, but for the very small use case that we have those seem like a bit of an overkill. I think this will work fine for the time being.
